### ISSUE TITLE
Sample app

### ISSUE THREAD

**Issue by PeterWone** [jmzagorski/aurelia-fontawesome#1]
**I'm submitting a feature request**

This is a gorgeous piece of work. From reading the readme.md it looks like you've catered for efficiency in every major use case. Sadly I couldn't get it to work, which is undoubtedly a failure on my part, but I don't know where. A worked example app would have greatly helped because it would implicitly document small but important ambient details.

**Comment by jmzagorski** [comment]
See if this helps...https://github.com/jmzagorski/aurelia-fontawesome-samples
