### ISSUE TITLE
Webpack plugin

### ISSUE THREAD

**Issue by rmja** [jmzagorski/aurelia-fontawesome#7]
**I'm submitting a feature request**

* **Library Version:**
0.1.0

* **Browser:**
all

**Current behavior:**
One has to manually bind an icon directly or add them to the font awesome library in advance

**What is the expected behavior?**
It would be really cool if a simple webpack plugin could be made which would add the icon dependencies simply from the view, such that e.g. `<font-awesome-icon icon="camera"></font-awesome-icon>` would simply include the `faCamera` icon as a dependency to the view and either 1) add it to the font awesome library or 2) bind it directly to the element.

**What is the motivation / use case for changing the behavior?**
It would drastically simplify the use of the custom element.

**Comment by jmzagorski** [comment]
That is a great feature, and I am sure other font awesome plugins would benefit from that too. I have no experience writing webpack plugins so I am not sure I am the best person for that. My guess is that if you could get that to work for this plugin, you may be able to get it to work for the react/vue/angular plugins as well?

**Comment by rmja** [comment]
I will have a look at it when I find time. I guess it could be generic if the plugin simply ensures that the requested icons are added to the fa library.

**Comment by rmja** [comment]
I have created a webpack loader that does this: https://github.com/rmja/aurelia-fontawesome-loader

**Comment by jmzagorski** [comment]
Great job! I have this library in one app under development, so when I can get back to it I will be sure to add your plugin. I will add a link to your repo in the REAMDE,
